<?php Yaf\loader::import(__HEADER__); ?>

<div class="row">
    <div class="col-xs-12">
        <!-- PAGE CONTENT BEGINS -->
        <div class="row">
            <div class="col-xs-12">
                <div>
                    <button class="btn btn-xs  btn-success" id="addForm" dialog-title="增加奖品" data-dialog="myDialog" data-action="<?php echo base_url('admin/prize/add'); ?>">
                        <i class="ace-icon fa  fa-plus bigger-110"></i>
                        <span class="bigger-110 no-text-shadow">新增</span>
                    </button>
                    <button class="btn btn-xs   btn-warning" id="editForm" dialog-title="编辑奖品" data-pk="p_id" data-dialog="myDialog" data-info-url="<?php echo base_url('admin/prize/getPrizeById'); ?>" data-action="<?php echo base_url('admin/prize/edit'); ?>">
                        <i class="ace-icon fa fa-pencil bigger-110"></i>
                        <span class="bigger-110 no-text-shadow">编辑</span>
                    </button>
                    <button class="btn btn-xs   btn-danger" id="delForm" data-pk="p_id" data-action="<?php echo base_url('admin/prize/del'); ?>">
                        <i class="ace-icon glyphicon glyphicon-trash bigger-110"></i>
                        <span class="bigger-110 no-text-shadow">删除</span>
                    </button>
                </div>
            </div>
        </div>
        <div class="hr hr-10 dotted"></div>

        <div class="row">
            <div class="col-xs-12">
                <table id="table"
                       class="table table-striped table-bordered table-hover"
                       data-click-to-select="true"
                       data-page-size="<?php echo $limit; ?>"
                       data-toggle="table"
                       data-url="<?php echo base_url('admin/prize/getList'); ?>"
                       data-side-pagination="server"
                       data-pagination="true"
                       data-page-list="[<?php echo $limit; ?>]"
                >
                    <thead>
                    <tr>
                        <th data-checkbox="true" data-class="center"></th>
                        <th data-field="p_name">名称</th>
                        <th data-field="p_inventory">库存</th>
                        <th data-field="p_image_uri">奖品图片</th>
                        <th data-field="create_time">添加时间</th>
                        <th data-field="username"> 添加人</th>
                        <th data-field="p_probability">概率</th>
                    </tr>
                    </thead>
                </table>
            </div><!-- /.span-->
        </div><!-- /.row -->

        <script type="text/html" id="myDialog">
            <div class="row">
                <div class="col-xs-12">
                    <form id="myForm" action="<%=data.action%>" method="post">
                        <div class="form-horizontal">
                            <div class="form-group">
                                <label class="col-sm-3 control-label no-padding-right" for="name"> 奖品名称</label>

                                <div class="col-sm-6">
                                    <input type="text" name="p_name" placeholder="奖品名称" class="col-xs-12" value="<%=data.info.p_name%>" required/>
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="col-sm-3 control-label no-padding-right" for="show_index"> 奖品库存叠加值</label>

                                <div class="col-sm-6">
                                    <label><%=data.info.p_inventory%></label>
                                    <input type="text" name="p_inventory" placeholder="奖品库存叠加值(正数为加，负数为减)" class="col-xs-12"/>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-3 control-label no-padding-right" for="show_index"> 奖品图片</label>

                                <div class="col-sm-6">
                                    <input type="file" id="p_image_uri" name="p_image_uri" placeholder="奖品库存叠加值(正数为加，负数为减)" class="col-xs-12"/>
                                    <%if(data.info.p_image_uri){%>
                                    <img src="<?php echo getFileUrl('<%=data.info.p_image_uri%>'); ?>" width="100">
                                    <%}%>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-3 control-label no-padding-right" for="show_index"> 奖品概率</label>

                                <div class="col-sm-6">
                                    <input type="text" id="p_probability" name="p_probability" placeholder="概率,这里概率是要用来计算得到最后列表的实际概率" class="col-xs-12" value="<%=data.info.p_probability%>"/>
                                </div>
                            </div>
                            <div class="form-group">
                                <input type="hidden" value="<%=data.info.p_id%>" name="p_id">
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </script>
    </div><!-- /.col -->
</div><!-- /.row -->

<?php Yaf\loader::import(__FOOTER__); ?>

<script>
    $.hight_nav('<?php echo base_url('admin/prize/index');?>');
    $(function (e) {
        yboard.init();
    });
    function getFormData(obj, callBack) {
        var dataAction = obj.attr('data-action'), dataInfoUrl = obj.attr('data-info-url'), formData = {
            action: dataAction,
            info: {
                p_id: '',
                p_name: '',
                p_inventory: '',
                p_image_uri: '',
                p_probability: ''
            }
        };
        if (typeof (dataInfoUrl) != 'undefined' && dataInfoUrl != '') {
            var p_id = $($(yboard.config.tableId)).getListIds('p_id', true);
            if (!p_id) {
                return false;
            }
            $.get(dataInfoUrl, {p_id: p_id}, function (data) {
                if (data.code == 200) {
                    formData = {
                        action: dataAction,
                        info: {
                            p_id: data.data.p_id,
                            p_name: data.data.p_name,
                            p_inventory: data.data.p_inventory,
                            p_image_uri: data.data.p_image_uri,
                            p_probability: data.data.p_probability
                        }
                    };
                    callBack(formData);
                }
            }, 'json');
        } else {
            callBack(formData);
        }
    }
    function dialogShow() {
        $('input[type=file]').ace_file_input({
            no_file: '文件上传 ...',
            btn_choose: '选择',
            btn_change: '更改',
            droppable: false,
            onchange: null,
            thumbnail: false
        });
    }
</script>
</body>
</html>