</div><!-- /.page-content -->
</div>
</div><!-- /.main-content -->

<div class="footer">
    <div class="footer-inner">
        <div class="footer-content">
						<span class="bigger-120">
							<span class="blue bolder">lottery.yboard.cn</span>
							版权 &copy; 2016-2016
						</span>
        </div>
    </div>
</div>

<a href="#" id="btn-scroll-up" class="btn-scroll-up btn btn-sm btn-inverse">
    <i class="ace-icon fa fa-angle-double-up icon-only bigger-110"></i>
</a>
</div><!-- /.main-container -->

<!--[if !IE]> -->
<script src="<?php echo __ASSETS__; ?>/js/jquery.2.1.1.min.js"></script>

<!-- <![endif]-->

<!--[if IE]>
<script src="<?php echo __ASSETS__;?>/js/jquery.1.11.1.min.js"></script>
<![endif]-->

<!--[if !IE]> -->
<script type="text/javascript">
    window.jQuery || document.write("<script src='<?php echo __ASSETS__;?>/js/jquery.min.js'>" + "<" + "/script>");
</script>

<!-- <![endif]-->

<!--[if IE]>
<script type="text/javascript">
    window.jQuery || document.write("<script src='<?php echo __ASSETS__;?>/js/jquery1x.min.js'>" + "<" + "/script>");
</script>
<![endif]-->
<script type="text/javascript">
    if ('ontouchstart' in document.documentElement) document.write("<script src='<?php echo __ASSETS__;?>/js/jquery.mobile.custom.min.js'>" + "<" + "/script>");
</script>
<script src="<?php echo __ASSETS__;?>/js/bootstrap.min.js"></script>
<script src="<?php echo __ASSETS__;?>/js/bootbox.min.js"></script>
<script src="<?php echo __ASSETS__;?>/js/bootstrap-datepicker.min.js"></script>
<script src="<?php echo __ASSETS__;?>/bootstrap-table/bootstrap-table.min.js"></script>
<script src="<?php echo __ASSETS__;?>/bootstrap-table/locale/bootstrap-table-zh-CN.min.js"></script>
<script src="<?php echo __JS__; ?>/jquery.form.min.js"></script>

<script src="<?php echo __ASSETS__;?>/js/jquery.validate.min.js"></script>
<script src="<?php echo __ASSETS__;?>/js/additional-methods.min.js"></script>
<script src="<?php echo __JS__; ?>/plugin/jquery-validate/localization/messages_zh.min.js"></script>

<script src="<?php echo __ASSETS__;?>/js/dropzone.min.js"></script>
<!-- ace scripts -->
<script src="<?php echo __ASSETS__;?>/js/ace-elements.min.js"></script>
<script src="<?php echo __ASSETS__;?>/js/ace.min.js"></script>
<script src="<?php echo __JS__; ?>/artTemplate.js"></script>
<script src="<?php echo __JS__; ?>/common.js"></script>
<script src="<?php echo __JS__; ?>/admin.js"></script>
