<?php Yaf\loader::import(__HEADER__); ?>

<div class="row">
    <div class="col-xs-12">
        <!-- PAGE CONTENT BEGINS -->
        <div class="row">
            <div class="col-xs-12">
                <div>
                    <button class="btn btn-xs  btn-success" id="addForm" dialog-title="增加用户" data-dialog="myDialog" data-action="<?php echo base_url('admin/member/add'); ?>">
                        <i class="ace-icon fa  fa-plus bigger-110"></i>
                        <span class="bigger-110 no-text-shadow">新增</span>
                    </button>
                    <button class="btn btn-xs   btn-warning" id="editForm" dialog-title="编辑用户" data-pk="m_uid" data-dialog="myDialog" data-info-url="<?php echo base_url('admin/member/getMemberById'); ?>" data-action="<?php echo base_url('admin/member/edit'); ?>">
                        <i class="ace-icon fa fa-pencil bigger-110"></i>
                        <span class="bigger-110 no-text-shadow">编辑</span>
                    </button>
                    <button class="btn btn-xs   btn-danger" id="delForm" data-pk="m_uid" data-action="<?php echo base_url('admin/member/del'); ?>">
                        <i class="ace-icon glyphicon glyphicon-trash bigger-110"></i>
                        <span class="bigger-110 no-text-shadow">删除</span>
                    </button>
                </div>
            </div>
        </div>
        <div class="hr hr-10 dotted"></div>

        <div class="row">
            <div class="col-xs-12">
                <table id="table"
                       class="table table-striped table-bordered table-hover"
                       data-click-to-select="true"
                       data-page-size="<?php echo $limit; ?>"
                       data-toggle="table"
                       data-url="<?php echo base_url('admin/member/getList'); ?>"
                       data-side-pagination="server"
                       data-pagination="true"
                       data-page-list="[<?php echo $limit; ?>]"
                >
                    <thead>
                    <tr>
                        <th data-checkbox="true" data-class="center"></th>
                        <th data-field="m_username">用户名</th>
                        <th data-field="m_phone">电话号码</th>
                        <th data-field="m_ip">来路ip</th>
                        <th data-field="create_time">添加时间</th>
                        <th data-field="m_email"> 邮箱</th>
                    </tr>
                    </thead>
                </table>
            </div><!-- /.span-->
        </div><!-- /.row -->

        <script type="text/html" id="myDialog">
            <div class="row">
                <div class="col-xs-12">
                    <form id="myForm" action="<%=data.action%>" method="post">
                        <div class="form-horizontal">
                            <div class="form-group">
                                <label class="col-sm-3 control-label no-padding-right" for="m_username"> 用户名称</label>

                                <div class="col-sm-6">
                                    <input type="text" name="m_username" placeholder="用户名称" class="col-xs-12" value="<%=data.info.m_username%>" required/>
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="col-sm-3 control-label no-padding-right" for="show_index"> 用户邮箱</label>

                                <div class="col-sm-6">
                                    <input type="text" name="m_email" placeholder="用户邮箱" class="col-xs-12" value="<%=data.info.m_email%>"/>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-3 control-label no-padding-right" for="m_phone"> 用户电话</label>

                                <div class="col-sm-6">
                                    <input type="text" id="m_phone" name="m_phone" placeholder="用户电话" class="col-xs-12" value="<%=data.info.m_phone%>"/>
                                </div>
                            </div>
                            <div class="form-group">
                                <input type="hidden" value="<%=data.info.m_uid%>" name="m_uid">
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </script>
    </div><!-- /.col -->
</div><!-- /.row -->

<?php Yaf\loader::import(__FOOTER__); ?>

<script>
    $.hight_nav('<?php echo base_url('admin/member/index');?>');
    $(function (e) {
        yboard.init();
    });
    function getFormData(obj, callBack) {
        var dataAction = obj.attr('data-action'), dataInfoUrl = obj.attr('data-info-url'), formData = {
            action: dataAction,
            info: {
                m_uid: '',
                m_username: '',
                m_phone: '',
                m_ip: '',
                m_email: ''
            }
        };
        if (typeof (dataInfoUrl) != 'undefined' && dataInfoUrl != '') {
            var m_uid = $($(yboard.config.tableId)).getListIds('m_uid', true);
            if (!m_uid) {
                return false;
            }
            $.get(dataInfoUrl, {m_uid: m_uid}, function (data) {
                if (data.code == 200) {
                    formData = {
                        action: dataAction,
                        info: {
                            m_uid: data.data.m_uid,
                            m_username: data.data.m_username,
                            m_phone: data.data.m_phone,
                            m_ip: data.data.m_ip,
                            m_email: data.data.m_email
                        }
                    };
                    callBack(formData);
                }
            }, 'json');
        } else {
            callBack(formData);
        }
    }
</script>
</body>
</html>