<?php loadFile(__HEADER__); ?>

<div class="row">
    <div class="col-xs-12">
        <!-- PAGE CONTENT BEGINS -->
        <div class="row">
            <div class="col-xs-12">
                <div>
                    <button class="btn btn-xs  btn-success" id="addForm" dialog-title="增加管理员" data-dialog="myDialog" data-action="<?php echo base_url('admin/admins/add'); ?>">
                        <i class="ace-icon fa  fa-plus bigger-110"></i>
                        <span class="bigger-110 no-text-shadow">新增</span>
                    </button>
                    <button class="btn btn-xs   btn-warning" id="editForm" dialog-title="编辑管理员" data-pk="a_uid" data-dialog="myDialog" data-info-url="<?php echo base_url('admin/admins/getAdminById'); ?>" data-action="<?php echo base_url('admin/admins/edit'); ?>">
                        <i class="ace-icon fa fa-pencil bigger-110"></i>
                        <span class="bigger-110 no-text-shadow">编辑</span>
                    </button>
                    <button class="btn btn-xs   btn-danger" id="delForm" data-pk="a_uid" data-action="<?php echo base_url('admin/admins/del'); ?>">
                        <i class="ace-icon glyphicon glyphicon-trash bigger-110"></i>
                        <span class="bigger-110 no-text-shadow">删除</span>
                    </button>
                </div>
            </div>
        </div>
        <div class="hr hr-10 dotted"></div>

        <div class="row">
            <div class="col-xs-12">
                <table id="table"
                       class="table table-striped table-bordered table-hover"
                       data-click-to-select="true"
                       data-page-size="<?php echo $limit; ?>"
                       data-toggle="table"
                       data-url="<?php echo base_url('admin/admins/getList'); ?>"
                       data-side-pagination="server"
                       data-pagination="true"
                       data-page-list="[<?php echo $limit; ?>]"
                >
                    <thead>
                    <tr>
                        <th data-checkbox="true" data-class="center"></th>
                        <th data-field="a_account">名称</th>
                        <th data-field="a_password">密码</th>
                        <th data-field="create_time">添加时间</th>
                    </tr>
                    </thead>
                </table>
            </div><!-- /.span-->
        </div><!-- /.row -->

        <script type="text/html" id="myDialog">
            <div class="row">
                <div class="col-xs-12">
                    <form id="myForm" action="<%=data.action%>" method="post">
                        <div class="form-horizontal">
                            <div class="form-group">
                                <label class="col-sm-3 control-label no-padding-right" for="name"> 用户名</label>

                                <div class="col-sm-6">
                                    <input type="text" name="a_account" placeholder="用户名" class="col-xs-12" value="<%=data.info.a_account%>" required/>
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="col-sm-3 control-label no-padding-right" for="show_index"> 密码</label>

                                <div class="col-sm-6">
                                    <input type="text" name="a_password" placeholder="密码" class="col-xs-12"/>
                                </div>
                            </div>
                            <div class="form-group">
                                <input type="hidden" value="<%=data.info.a_uid%>" name="a_uid">
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </script>
    </div><!-- /.col -->
</div><!-- /.row -->

<?php loadFile(__FOOTER__); ?>

<script>
    $.hight_nav('<?php echo base_url('admin/admins/index');?>');
    $(function (e) {
        yboard.init();
    });
    function getFormData(obj, callBack) {
        var dataAction = obj.attr('data-action'), dataInfoUrl = obj.attr('data-info-url'), formData = {
            action: dataAction,
            info: {
                a_uid: '',
                a_account: ''
            }
        };
        if (typeof (dataInfoUrl) != 'undefined' && dataInfoUrl != '') {
            var a_uid = $($(yboard.config.tableId)).getListIds('a_uid', true);
            if (!a_uid) {
                return false;
            }
            $.get(dataInfoUrl, {a_uid: a_uid}, function (data) {
                if (data.code == 200) {
                    formData = {
                        action: dataAction,
                        info: {
                            a_uid: data.data.a_uid,
                            a_account: data.data.a_account
                        }
                    };
                    callBack(formData);
                }
            }, 'json');
        } else {
            callBack(formData);
        }
    }
    function dialogShow() {
        return false;
    }
</script>
</body>
</html>